version: '3.7'

services:
  kassa-ui:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/opt/app-root/src/src
    container_name: verkkokauppa-kassa-ui
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn dev
    environment:
      - SERVICE_NAME=verkkokauppa-kassa-ui
      - VIRTUAL_PORT=8080
  