version: '3.7'

services:
  kassa-ui:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/opt/app-root/src/src
      - ./webpack.config.js:/opt/app-root/webpack.config.js
      - ./tsconfig.json:/opt/app-root/tsconfig.json
    container_name: verkkokauppa-kassa-ui
    expose:
      - '8080'
      - '3000'
    ports:
      - '8080:8080'
      - '3000:3000'
    command: yarn start:docker
    environment:
      - SERVICE_NAME=verkkokauppa-kassa-ui
      - VIRTUAL_PORT=8080
      - REACT_APP_PAYMENT_API_URL=https://talpa-verkkokauppa-payment-experience-api-dev.apps.arodevtest.hel.fi/
      - REACT_APP_ORDER_API_URL=https://talpa-verkkokauppa-order-experience-api-dev.apps.arodevtest.hel.fi/
      - REACT_APP_MERCHANT_API_URL=https://talpa-verkkokauppa-merchant-experience-api-dev.apps.arodevtest.hel.fi/
